---
title: "google_analytics"
author: "Siran Zhao"
date: "September 16, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(jsonlite)
library(dplyr)
library(purrr)
library(tidyr)
library(data.table)
library(stringi)
```


```{r}

raw_data <- read.csv("D:/All Files/BU/Kaggle/Google Analytics/Google-Analytics-Customer-Revenue-Prediction/train.csv", stringsAsFactors = FALSE)
#trafficSource
df_traffic <- raw_data %>%
  select(fullVisitorId, trafficSource)



df_traffic_p_1 <- df_traffic %>% 
  mutate(trafficSource = map(trafficSource, ~ fromJSON(.) %>% map(1) %>% as_tibble() )) %>% unnest(trafficSource)

saveRDS(df_traffic_p_1,"df_traffic_p.rds")

unique(df_traffic[,2])

b <- df_traffic_p
a <- df_traffic[683202,2]%>%fromJSON()



```

```{r}
out_file <- file("file.csv", open="a")  #creates a file in append mode

close(out_file)
```


```{r}
unique(df_traffic_p_1$campaign)
sum(df_traffic_p_1["campaign"] == "(not set)")

```

```{r}
unique(df_traffic_p_1$source)
sum(df_traffic_p_1["source"] == "google")

```


```{r}
unique(df_traffic_p_1$medium)
sum(df_traffic_p_1["medium"] == "organic")
```


```{r}
unique(df_traffic_p_1$keyword)

```


```{r}
unique(df_traffic_p_1$adwordsClickInfo)
sum(df_traffic_p_1["adwordsClickInfo"] == "not available in demo dataset")

#most of the data were not available
```

```{r}
unique(df_traffic_p_1$isTrueDirect)
sum(is.na(df_traffic_p_1["isTrueDirect"]))
```

```{r}
unique(df_traffic_p_1$referralPath)
sum(is.na(df_traffic_p_1["referralPath"]))
```

```{r}
unique(df_traffic_p_1$adContent)
sum(is.na(df_traffic_p_1["adContent"]))

```

```{r}
unique(df_traffic_p_1$campaignCode)
sum(is.na(df_traffic_p_1["campaignCode"]))
#removed because is just contain 2 levels and most of them are NA
```

```{r}

adwordsClickInfo
campaignCode

```


```{r}
df_traffic_p_2 <- df_traffic_p_1[-c("adwordsClickInfo","campaignCode")]

df_traffic_p_2 <- df_traffic_p_1[-c(which(colnames(df_traffic_p_1) == c("adwordsClickInfo")))]

df_traffic_p_2 <- df_traffic_p_2[-c(which(colnames(df_traffic_p_2) == c("campaignCode")))]

saveRDS(df_traffic_p_2,"df_traffic_p_2.rds")
```


